FROM node:18-alpine

WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

ENV PORT 3001
EXPOSE 3001

ENV SEED_USERBASE_SIZE=5
ENV SEED_CONTACTS_PER_USER=3
ENV SEED_PAYMENTS_PER_USER=15
ENV SEED_REQUESTS_PER_USER=10
ENV SEED_BANK_ACCOUNTS_PER_USER=1
ENV SEED_LIKES_PER_USER=2
ENV SEED_COMMENTS_PER_USER=2
ENV SEED_NOTIFICATIONS_PER_USER=5
ENV SEED_BANK_TRANSFERS_PER_USER=5
ENV SEED_DEFAULT_USER_PASSWORD=s3cret
ENV PAGINATION_PAGE_SIZE=10

CMD ["yarn", "tsnode", "--files", "backend/app.ts"]
