version: "0.1"

apps:
  frontend:
    module: nullstone/aws-fargate-service
    vars: {}
  backend:
    module: nullstone/aws-fargate-service
    vars: {}
    connections:
      cluster-namespace: namespace0
    environment:
      CORS_ORIGINS: "https://app.realworld.{{ NULLSTONE_ENV }}.nullst.one"
  migrations:
    module: nullstone/aws-fargate-task
    vars: {}
    connections:
      cluster-namespace: namespace0
    environment:
      SEED_USERBASE_SIZE: "5"
      SEED_CONTACTS_PER_USER: "3"
      SEED_PAYMENTS_PER_USER: "15"
      SEED_REQUESTS_PER_USER: "10"
      SEED_BANK_ACCOUNTS_PER_USER: "1"
      SEED_LIKES_PER_USER: "2"
      SEED_COMMENTS_PER_USER: "2"
      SEED_NOTIFICATIONS_PER_USER: "5"
      SEED_BANK_TRANSFERS_PER_USER: "5"
      SEED_DEFAULT_USER_PASSWORD: "s3cret"
      PAGINATION_PAGE_SIZE: "10"
